### ISSUE TITLE
Use Wireguard for encrypted links

### ISSUE THREAD

**Issue by tomberek** [NixOS/nixops#1040]
Current SSH tunnels are convenient, but the option to use wireguard would be very nice. I am willing to implement. Would anyone be interested in collaborating?

**Comment by tomberek** [comment]
#1048 is the beginning to allow arbitrary resources like WireGuard keys. Biggest concern is #959, access to resources during phase 1.

**Comment by RaitoBezarius** [comment]
I'm super interested in this as well, @tomberek what's left to do?

**Comment by tomberek** [comment]
I implemented this in a custom and fragile way using some the the PRs I mentioned. Basically the private key material for NixOps (ssh or this) needs to be managed in some way outside of the normal system closure. Either specified in such a way that minimizes it being in the NixStore or fully managed outside of it. 

It’s doable right now with a bit of effort, but I’m not using NixOps at the moment so it will be hard to find time. 

Perhaps a good first step is to review the WireGuard NixOS module in Nixpkgs and see if it has all the features we need? See if any feature could be added that would make NixOps use easier? (Using various alternate sources/distribution for key material?)

**Comment by RaitoBezarius** [comment]
At the moment, I'm writing a solution using WireGuard NixOS module which I find "good enough" for my use-case, what's a bit annoying is to have to manage:
- private key, public key manually (so I put them into my secrets system with `/run/keys`)
- IPs propagation between nodes, I have to pass the IP manually between all hosts, I can reuse some stuff

What would be great is to make so that the NixOS module to derive the public key and make it available as a resource from the private key file during phase 1 or 2, so that it's trivial to propagate server's public key to peers and the same in the other way, to propagate peers' public key to server.

**Comment by tomberek** [comment]
That’s exactly the issues I ran into and became the impetus for the “arbitrary resource” and “expose resources to deployment.keys” PRs. 

Another possibility is to piggyback on the encryptedLinks feature and make a service? Service would create keys and announce via the ssh links to broadcast the correct settings. Upon receiving all settings it would establish the full mesh of Wireguard connections? Hrm. Seems hacky.

**Comment by RaitoBezarius** [comment]
I came to WireGuard because encryptedLinks does not work very well, it
assumes some stuff on your private IP apparently (192.168.(105 + index %
256).(index % 256) from what I gather) and that's why I wanted something
more flexible and solid, e.g. WireGuard.

**Comment by grahamc** [comment]
See #1293 and #1294.
