### ISSUE TITLE
Disable sandbox per deployment

### ISSUE THREAD

**Issue by arximboldi** [NixOS/nixops#1479]
Hi!

I need a deployment that sadly needs to disable the sandbox because some packages for now require fetching stuff from the Internet. While I would love to solve that soon, in the meanwhile I need to disable the sandbox.

The documentation only states that you can do this with `nix.conf`. Is there a more local way to do this, with a command line argument or environment variable? Maybe can I even just do it from the deployment .nix files, disabling it only for the machines that need this?

**Comment by arximboldi** [comment]
Ok, I see that `--option sandbox false` does work, but setting `NIX_CONF_DIR` does not work.

I guess in the future I will be able to use `NIX_USER_CONF_FILES` as mentioned here: https://github.com/NixOS/nix/issues/3723

**Comment by roberth** [comment]
I recommend not to do this. You are making your builds unreproducible and putting yourself at risk of getting into a situation where you can not change your software without knowing what else changes and you are more likely to run into problems when making a change because your build will depend on external influences much more than necessary.
