### ISSUE TITLE
unix_listener: path too long for Unix domain socket

### ISSUE THREAD

**Issue by PAI5REECHO** [NixOS/nixops#1513]
I'm still running into #340 occasionally: `unix_listener: path "/tmp/nix-shell.Ha8P5f/nix-shell.FZB0NA/nix-shell.2SSHVY/nixops-ssh-tmp1ytrqnz8/master-socket.plhfkveObYlV2xBh" too long for Unix domain socket`

**Comment by roberth** [comment]
My first guess is that you've entered into a shell that modifies TMP/TEMPDIR/... on each invocation. `ps` may reveal a number of `bash` processes representing these nested shells. If that's the case, you may be able to avoid this by quitting your `nix-shell` instead of opening a new nested one in the existing `nix-shell` session.
