### ISSUE TITLE
Nixpkgs marked poetry to be insecure (indirectly).

### ISSUE THREAD

**Issue by Pegasust** [NixOS/nixops#1548]
See https://github.com/NixOS/nixpkgs/pull/203396#issuecomment-1329362168

Not sure how I'd contribute to fix this issue though. My guess is a simple `nix flake update` might work?

**Comment by scottbot95** [comment]
Tangentially related question, but I'm curious if there's any reason why the version of nixpkgs in use is `nixos-unstable`? Looks like it's been on the unstable branch since introduction of flakes. I'm certainly no flake expert, but wouldn't it be better to use a stable release if we don't specifically need something form unstable?
