### ISSUE TITLE
Feature request: Keep a GC root on the build.

### ISSUE THREAD

**Issue by ambrop72** [NixOS/nixops#272]
As part of a Nix garbage collection, the derivations that were used to perform a deployment may be deleted. Then, even a minor configuration change to a deployment may require lots of rebuilding (or downloads from the cache).

I imagine the full solution would be nixops-level generation management, pretty much like NixOS does it.

**Comment by edolstra** [comment]
This is already possible by setting `network.enableRollback = true` in the network spec. This will create a profile in `/nix/var/nix/profiles/per-user/<username>/nixops/<uuid>` that keeps track of each generation of the configuration.

Looks like it's not documented though.

**Comment by aszlig** [comment]
Closing in favor of #372.

**Comment by jerith666** [comment]
`network.enableRollback=true` certainly kept `nix-collect-garbage` from deleting all the nixops store paths.

Since it isn't documented yet (:smile:), I can't say for sure, but based on the name of the option, it may be overkill for what's desired here, though.  In my case, I don't necessarily want to keep the same amount of history for nixops networks as I do for local machine images.  I'd probably be okay with just 1 or 2 previous images, whereas on my desktop machines I typically keep the past 30 days' worth of images.  I.e. what I really want is a way to pass different `--delete-older-than` options to `nix-collect-garbage` for local vs. nixops store paths.  Hopefully that makes sense ... LMK if it's worth filing a separate issue about this.
