### ISSUE TITLE
Add support for certificate provisioning

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixops#283]
Let's Encrypt (https://letsencrypt.org/) should make it possible to obtain SSL certificates automatically. It would be nice if NixOps could provision certificates via Let's Encrypt.

Something like this:
```
resources.certificates."example.org".obtainFrom = "machine";

machine = 
  { config, pkgs, resources, ... }:
  { deployment.targetEnv = "ec2";
    deployment.route53.hostName = "example.org";

    services.httpd = {
      enable = true;
      enableSSL = true;
      sslServerCert = resources.certificates."example.org".certificate;
      sslServerKey = resources.certificates."example.org".key;
    };
  };
```
Here NixOps would first create `machine` (without building the configuration), bind it to `example.org` in DNS, run the ACME client on `machine` to generate a certificate for `example.org`, and finally build/activate the configuration that uses the generated certificate.

**Comment by domenkozar** [comment]
Well, we might be one step closer: https://github.com/NixOS/nixpkgs/commit/b8d9a16eecb82e05cc937aaf07566b0bfa27a36e

**Comment by disassembler** [comment]
I kinda think you'd want this functionality on the nixos layer instead of nixops. @domenkozar I'd be interested in digging into this a bit. Could you point me at where would be best in nixpkgs to have the generator that invokes letsencrypt for the ssl cert/key? The other question is how would we detect if the cert is expired and needs regenerated (letsencrypt has a 90 day certificate lifespan). when we do a rebuild-switch should we check if the cert expires in 30 days, and if so, regenerate? Or should we have every rebuild-switch trigger a new cert request?

**Comment by edolstra** [comment]
Well, NixOS doesn't really have facilities for provisioning / keeping track of resources. It could be done in the activation script or a systemd job, however.

**Comment by jgillich** [comment]
LE certs only last 90 days, so you'd need a cron job or something like that to renew them. Also, the official client is not [very automation friendly](https://news.ycombinator.com/item?id=10672539), but there are tons of alternatives like [simp_le](https://github.com/kuba/simp_le).

**Comment by CMCDragonkai** [comment]
A systemd service would be better at handling this than Nix directly, also more general than NixOps.

**Comment by Mayeu** [comment]
Just a head up here, that this has been implemented into NixOS as an ACME service, see [issue 11506](https://github.com/NixOS/nixpkgs/pull/11506) on nixpkgs.

This could closed then?

**Comment by kevincox** [comment]
I'm going to recommend closing this as the NixOS feature is probably more then enough.

**Comment by eqyiel** [comment]
I think this still has potential! The ACME service is good but it needs bootstrapping.  If you're using that the first deployment will fail to start all services, you'd need to SSH in to manually run the ACME service and restart anything that depends on the certificates.  Unless I'm missing something you also need a second HTTP server with no SSL configured just to serve the challenges, otherwise you won't be able to start it at all.

**Comment by kevincox** [comment]
> Unless I'm missing something you also need a second HTTP server with no SSL configured just to serve the challenges, otherwise you won't be able to start it at all.

You aren't wrong. In my deployment I'm running a separate nginx on all of my nodes that does exactly two things:
- If the request is for `/.well-known/acme-challange/*` proxy the request to the current "ACME Master"
- Otherwise redirect to the same URL over SSL.

Otherwise you get a dependency cycle between the webserver and the ACME client.

The alternative is using something like DNS but then you have to support different providers. I'm considering this option but in my case it has the downside that I need to be able to control the DNS where my current setup will gladly acquire certificates for any site that is pointed at my servers.

**Comment by eqyiel** [comment]
@kevincox that is exactly what I do, run a separate nginx that serves `/.well-known/acme-challenge/*` over HTTP and redirects everything else.

It's not ideal because each new deployment starts out with `httpd.service` failing, but to be fair I'm not sure what a better solution would look like.

**Comment by teozkr** [comment]
My current setup is that I have Nginx serving as both a reverse proxy and the ACME challenges, and a separate Haproxy instance that proxies Https to the Nginx instance. That way the Haproxy server can safely have a systemd dependency on the ACME client.

**Comment by domenkozar** [comment]
This is now implemented: https://github.com/NixOS/nixpkgs/pull/15562
