### ISSUE TITLE
Network-level configuration?

### ISSUE THREAD

**Issue by pikajude** [NixOS/nixops#304]
It would be useful to define configuration that applies to all machines in a network, like e.g. package overrides and shell aliases. Right now, afaict, configuration applies individually to each machine (and not its child containers).

**Comment by rbvermaa** [comment]
Since 23599d0ed434a3d0c1e83dc011cb9b448f44faa7, nixops supports a defaults attribute which applies the configuration specified in this attribute to all machines in the network. I can't find this in the docs though, so perhaps we should rename this issue to reflect that documentation needs to be added for this feature.

**Comment by pikajude** [comment]
Does that attribute apply to containers too?

**Comment by rbvermaa** [comment]
Ah, I misunderstood your original issue. This is more of a design issue/question for nixos, in stead of nixops. Please write to the mailinglist or create an issue in the nixpkgs issue tracker. Nixops only knows about the (first-class) resources it deploys.

**Comment by pikajude** [comment]
That's fine. It doesn't look like `imports` does anything when it's present in `defaults` though, which is the main reason I wanted this feature (I have my package overrides in a separate file that should be imported by every machine).

**Comment by pikajude** [comment]
My mistake, was assigning to `network.defaults` instead of `defaults`
