### ISSUE TITLE
Add support for VirtualBox 5.x

### ISSUE THREAD

**Issue by earldouglas** [NixOS/nixops#332]
On VirtualBox 5.x, `nixos deploy` hangs on `waiting for IP address`.

**Environments tested:**

Host: OSX 10.10
nix: 1.8 and 1.9
nixops: 1.2 and 1.3pre1524_d4828f4
VirtualBox: 5.0.2 (fails) 4.3 (works as expected)

Host: NixOS unstable
*I don't have access to the box right now, so I can't get versions, but everything is up to date as of 18 Aug 2015 via `nix-channel --update && nixos-rebuild switch`.*  I see the same `waiting for IP address` failure here.  I will try again with an older (4.x) VirtualBox and update this issue.

**Comment by rbvermaa** [comment]
Seems /VirtualBox/GuestInfo/Net/1/V4/IP property is not set.

**Comment by FlorianHeigl** [comment]
Same here, I can see the dhcp bit working fine in tcpdump -i vboxnet0.

```
00:27:30.096711 IP 192.168.56.100.bootps > broadcasthost.bootpc: BOOTP/DHCP, Reply, length 548
00:27:30.097202 IP 0.0.0.0.bootpc > broadcasthost.bootps: BOOTP/DHCP, Request from 08:00:27:00:49:dc (oui Unknown), length 334
00:27:30.097211 IP 0.0.0.0.bootpc > broadcasthost.bootps: BOOTP/DHCP, Request from 08:00:27:00:49:dc (oui Unknown), length 334
00:27:30.097263 IP 192.168.56.100.bootps > broadcasthost.bootpc: BOOTP/DHCP, Reply, length 548
00:27:30.097268 IP 192.168.56.100.bootps > broadcasthost.bootpc: BOOTP/DHCP, Reply, length 548
00:27:30.097594 ARP, Request who-has 192.168.56.103 tell 0.0.0.0, length 28
```

So, if that value isn't set, is it actually a VirtualBox bug?

**Comment by rbvermaa** [comment]
I am not sure. I tried using the NixOS OVA from the download page, and for that machine, the property is being set once booted (although it uses a different network setup).

**Comment by earldouglas** [comment]
Similar pattern here.  I fired up some instances via vagrant for an unrelated project, and they show the IP property being set correctly.

Could it be that the instances simply aren't getting IP addresses?  Is there an easy way to set the root password so I can log in via VirtualBox and run `ifconfig`?

**Comment by FlorianHeigl** [comment]
from a similar case I know the root password isn't going to be set at that stage, but I guess one could edit the image (via livecd)

Let's check if it is pingable via any ip from the subnet.

**Comment by ambrop72** [comment]
It seems the issue is that the guest property /VirtualBox/GuestInfo/Net/1/V4/IP is not being assigned, while the guest does actually receive the IP address.

This procedure can be used to change the root password:
- In GRUB, choose "e" to edit the boot options, and adjust init like this: init=<nixos-store-path>/sw/bin/bash (just change /init to /sw/bin/bash). Boot with ctrl+x. You should be dropped to a root shell shortly, but with no commands available due to PATH not being set properly.
- export PATH=${0%/bash}
- passwd
- mount -o remount,ro / && reboot -f

Now you can log in via the console and see the IP address with ifconfig.

Once the IP is known it is possible to do a hack to get nixops to continue. Do this on the host:
- VBoxManage list vms  (note the {VM_ID})
- VBoxManage guestproperty set VM_ID /VirtualBox/GuestInfo/Net/1/V4/IP IP_ADDRESS

I do not know why the property is not assigned or what in the guest is supposed to be responsible for assigning it.

**Comment by earldouglas** [comment]
Wow, thanks a lot for the workaround, @ambrop72 !

**Comment by domenkozar** [comment]
This is what nixops does: 
`nixops/backends/virtualbox.py:            ["VBoxManage", "guestproperty", "set", self.vm_id, "/VirtualBox/GuestInfo/Net/1/V4/IP", ''])`

**Comment by domenkozar** [comment]
I think we just need to upgrade VirtualBox images to use Virtualbox 5.0, as guest additions need to match.

**Comment by domenkozar** [comment]
Maybe virtualbox backend should try to upgrade guest additions?

**Comment by domenkozar** [comment]
This can be closed, I can confirm using latest nixops commit and `release-15.09` NixOS branch works.

**Comment by earldouglas** [comment]
Thank you!
