### ISSUE TITLE
chmod of keys can occur before group is created.

### ISSUE THREAD

**Issue by kevincox** [NixOS/nixops#362]
Occasionally when provisioning a new node I get the following error:

```
s10> uploading key ‘ssl_www.kevincox.ca.crt’...
s10> chown: invalid group: ‘root:ssl_www.kevincox.ca’
```

This can be worked around by:
1. Commenting out the key.
2. Deploying (creating the group).
3. Uncommenting the key.
4. Deploying.

**Comment by basvandijk** [comment]
The problem is that in [activate_configs(...)](https://github.com/NixOS/nixops/blob/130320aaecf26fc5cc161f8914fd95a9086d173c/nixops/deployment.py#L636) the keys are send (`m.send_keys()`) before activating the new configuration (`m.switch_to_configuration(...)`) and creating the needed users and groups. I guess this ordering makes sense because certain services may not function correctly if the needed keys are not present. 

The solution is probably to take the user and group configuration from the new configuration and only activate that part, then send the keys and finally activate the full new configuration.

**Comment by basvandijk** [comment]
Another idea I have is to set the key owner using the UID and GID instead of the user name and group name which doesn't require the user and group accounts to be installed.

I'm trying to do that [here](https://github.com/basvandijk/nixops/commit/a6d9690705c30fdffebdcf562248cc1770294c5d) but it's not working yet.

I'm probably doing something wrong with how I use my [setIds](https://github.com/basvandijk/nixops/blob/a6d9690705c30fdffebdcf562248cc1770294c5d/nix/keys.nix#L70) function.

Does somebody know why the `uid` property is not ending up in the XML file?

**Comment by basvandijk** [comment]
I've created a [pull request](https://github.com/NixOS/nixops/pull/369) which fixes this.

**Comment by basvandijk** [comment]
@aszlig had the following idea in #369 to fix this issue:

> ... a better idea probably would be to use (bind) mount units directly on each key (or maybe on /run/keys in the short run), so services depending on a particular key will block until it is available. That at least would prevent races and the need to explicitly depend on keys.target.

**Comment by ryanartecona** [comment]
I also just ran into this issue. Looking forward to a fix!

**Comment by kevincox** [comment]
Yeah, this is a massive pain when setting up new servers or services as instead of a single-step process I now have to edit my config to not set the group, deploy then revert the config and deploy a second time.

**Comment by ip1981** [comment]
I use IDs instead of names
```
user = toString allusers.${name}.uid;
```

**Comment by domenkozar** [comment]
See https://github.com/NixOS/nixops/pull/400
