### ISSUE TITLE
nixops does not provide nix-build with SSH credentials for OS X-based builds

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixops#483]
Creating separate issue for this, see https://github.com/NixOS/nixops/issues/260#issuecomment-92386829 and the history in that issue.

Right now, if you want to build a VM from OS X, you need get nixops to boot your VM, then SSH in, add your own SSH credentials, and only then building via the `NIX_REMOTE_SYSTEMS` will work.

NixOps should call nix-build with an environment that allows nix-build to use the NixOps SSH key.

**Comment by tomberek** [comment]
What are the full instructions for the "workaround?"

**Comment by kirelagin** [comment]
I am not really sure whether this issue is still relevant or not. (I’ve sent a longer email to the mailing list, it would be great if you could help me firure out all the details, @wmertens.)

With `NIX_REMOTE=` the remote building code in `nixops/deployment.py` kicks in and, in my case, the deployment succeeds without me having to do anything manually. Does this mean that his particular issue is resolved nowadays?

**Comment by wmertens** [comment]
Closing because it seems to have been fixed at some point.

**Comment by kirelagin** [comment]
It’s weird but now it does not work, I had to add my pwersonal key, to make `nixops deploy` ssh and build remotely 🤔.
