### ISSUE TITLE
Support Vultr

### ISSUE THREAD

**Issue by 3noch** [NixOS/nixops#575]
[Vultr](https://www.vultr.com/) is similar to DigitalOcean but it also supports image uploads.

**Comment by ravloony** [comment]
I was able to deploy to Vultr with no issues.

**Comment by 3noch** [comment]
@ravloony With nixops? How did you do it?

**Comment by ravloony** [comment]
This would be great. I was able to install NixOS on a Vultr instance.

**Comment by 3noch** [comment]
@ravloony Ah great! Yes Vultr would be an improvement even over DigitalOcean from NixOps POV.

**Comment by ravloony** [comment]
@3noch You're fast1 :-D I brain farted there. I was not able to deploy from NixOps, but only install from ISO.

**Comment by 3noch** [comment]
@ravloony Heh...just happened to be on GH at the right time. 

I don't know enough about NixOS internals but I'll bet Vultr would be one of the easier backends to implement.

**Comment by wmertens** [comment]
FYI they just added the NixOS 18.03 minimal ISO to the public library. So not quite NixOps support, but at least it's now feasible to make script that creates a NixOS VM from scratch without an existing snapshot.

**Comment by lihop** [comment]
Neat. However I can't find a way to create a server using an ISO from the ISO Library (I started [this discussion](https://discuss.vultr.com/discussion/1741/create-server-via-api-using-iso-from-iso-library#latest) about it on the Vultr forums).

While looking through the API docs I did notice the [/v1/iso/create_from_url](https://www.vultr.com/api/#iso_create_from_url) endpoint which allows you to upload a custom ISO to your account from a URL.

Unfortunately the public library ISO doesn't let you add an SSH key or run startup script, and because it's based on the official NixOS Minimal Installation CD, ssh is disabled by default, so the only way to access the server is through the web based KVM console.

**Comment by wmertens** [comment]
https://www.vultr.com/api/#server_create says you can pass an ISOID. You can also set the userdata with https://www.vultr.com/api/#server_set_user_data, which I would expect can be parsed by cloud-init

And then if https://github.com/NixOS/nixpkgs/issues/39076 gets traction, fully automated NixOS deployments on Vultr and others would be easy.

**Comment by wmertens** [comment]
ah, but the problem is finding the isoid for the public library :-/

**Comment by wmertens** [comment]
Looking at the deploy html, it turns out that the NixOS 18.03 ISO has the id `410303` :)

**Comment by wmertens** [comment]
I'd like to have the minimal ISO support user-data for auto-installing or maybe even auto-anything. It would be good to have some discussion at https://github.com/NixOS/nixpkgs/issues/39076

**Comment by grahamc** [comment]
Backends can be made in plugins now!
