### ISSUE TITLE
VirtualBox base image should be newer than 16.09

### ISSUE THREAD

**Issue by vaibhavsagar** [NixOS/nixops#835]
I tried to update `http://nixos.org/releases/nixos/virtualbox-nixops-images/virtualbox-nixops-${name}.vmdk.xz` to point to the latest 17.09 but it looks like that doesn't exist. Can this be updated?

**Comment by dtzWill** [comment]
:+1:! AFAICT a 16.09-based virtualbox image means we can only deploy to it if our nixpkgs are also 16.09 -- using newer versions (such as a currently supported NixOS version) has errors that appear to be due to mismatch in virtualbox or kerrnel version.

Until a new image is built, you can build your own locally and use that:
Looks like [this script](https://github.com/NixOS/nixops/blob/master/maintainers/build-virtualbox-image.sh) is how it would be updated, which I'm currently using (after commenting out the S3 copy) to build a suitable recent image.

You can then set `deployment.virtualbox.disks.disk1.baseImage = /path/to/new-image.vmdk;`.

**Comment by coretemp** [comment]
The script fails for me with 
```
copying staging root to image...
ioctl(KVM_CREATE_VM) failed: 16 Device or resource busy
failed to initialize KVM: Device or resource busy
```
Presumably, it only works when you are not using VirtualBox. The script should be able to select a suitable target VM technology (one that doesn't fail) and it shouldn't even try to do any work until it has checked its execution environment.

**Comment by zarybnicky** [comment]
Is there anything I can do to help move this forward?

**Comment by davidak** [comment]
After starting it says:

![screenshot from 2019-02-20 14-08-01](https://user-images.githubusercontent.com/91113/53093895-f6589b00-3518-11e9-98af-93d34b97ab18.png)

And it has 18.03 channel:

```
[root@webserver:~]# nix-channel --list
nixos https://nixos.org/channels/nixos-18.03
```

But it says it has the version 18.09 (current version):

```
[root@webserver:~]# nixos-version 
18.09.2203.9bd45dddf81 (Jellyfish)
```

After a reboot it shows even the new version and hostname:

![screenshot from 2019-02-20 14-12-04](https://user-images.githubusercontent.com/91113/53094128-98788300-3519-11e9-9d62-6fdc67b7745e.png)

Does that mean the base image is only for bootstrapping and NixOS is updated later?

**Comment by vaibhavsagar** [comment]
AFAIK yes, but it's still useful to have a newer base image!

**Comment by AmineChikhaoui** [comment]
@vaibhavsagar I added an 18.09 image yesterday https://github.com/NixOS/nixops/commit/09d0addfeca151c9c073af7454a06f2b0e73f594

**Comment by vaibhavsagar** [comment]
Perfect, thanks!

**Comment by DavHau** [comment]
For anyone ending up here because of base image issues, you can use this derivation to define your own up-to-date base image declaratively: https://github.com/DavHau/nixops-vbox-base-image
