### ISSUE TITLE
Deploying a NixOS 18.03 to a NixOS 17.09 host fails

### ISSUE THREAD

**Issue by fpletz** [NixOS/nixops#907]
nixops revision: 21955d1f36a5664f11de72d03f6359f3e1e89623

The Host is on 17.09 with Nix 1.11 and I'm trying to deploy 18.03 (with Nix 2.0) on there.

`nixops deploy` output:

```
aaa...> copying path '/nix/store/jmxa30cmdj8k3p8f20fxskp9iwfvxsaf-nixos-system-aaa-18.03.git.6b44b2ee32e' to 'ssh://root@aaa.bpletza.de'...
bpletza> closures copied successfully
aaa...> warning: unknown setting 'signed-binary-caches'
aaa...> waiting for exclusive access to the Nix store...
```

It will then wait indefinitely.

**Comment by aij** [comment]
I just tried and it worked for me, with nixops master 21955d1f36a5664f11de72d03f6359f3e1e89623, deploying nixos-18.03 0c52ab986be6cfe805edd3591917abb1cc48ea62 to a bare metal host that was previously on 17.09.

NixOps 1.5.2 did not work due to the `system.nixosVersion` renaming.

In case it makes a difference,  I did end up updating the client to 18.03 too, in hopes of getting a compatible nixops version... But instead found there hasn't been an updated nixops yet #898 .

So, I deployed 18.03 to a 17.09 host from an 18.03 host. I plan to repeat it a few more times before too long.

I'll try to get more scrollback next time. I saw the `warning: unknown setting 'signed-binary-caches'` message go by, but not `waiting for exclusive access to the Nix store...`.

**Comment by fpletz** [comment]
After stracing the nix-daemon I found out that the existence of `/nix/var/nix/db/big-lock` was the problem. As I didn't encounter the problem on any other hosts that I upgrade to 18.03 this might just be a weird random failure. Closing for now.
