### ISSUE TITLE
error: no AMI defined for EC2 machine

### ISSUE THREAD

**Issue by rsoeldner** [NixOS/nixops#910]
Hey,
when trying to deploy my application I receive `error: no AMI defined for EC2 machine 'backend'`
from the following configuration:

```
let
  region = "eu-west-1";
  accessKeyId = "bla";

  ec2 =
    { resources, ... }:
    { deployment.targetEnv = "ec2";
      deployment.ec2.accessKeyId = accessKeyId;
      deployment.ec2.region = region;
      deployment.ec2.instanceType = "m1.small";
      deployment.ec2.keyPair = resources.ec2KeyPairs.pk;
    };

in
{
 backend = ec2;

  resources.ec2KeyPairs.pl =
    { inherit region accessKeyId; };
}
```
Shouldn't this be enough ? 
Or do I need to specify a `channel` ?

**Comment by AmineChikhaoui** [comment]
Seems m1.* instance types are pv instances and not hvm which is not supported in recent NixOS versions (17.03/17.09).
So the evaluation defaults to "" if it doesn't find an AMI with that type https://github.com/NixOS/nixops/blob/master/nix/ec2.nix#L449. We probably can make it an explicit exception rather than a silent error that triggers later during the resource creatiion.
